# Generated by Django 3.2.5 on 2021-07-07 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Deportes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Deportek',
            new_name='Deportes',
        ),
    ]
